require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2

Gemspec/DevelopmentDependencies:
  Enabled: pending
  EnforcedStyle: gemspec
  SupportedStyles:
    - Gemfile
    - gems.rb
    - gemspec
  AllowedGems: [ ]
  Include:
    - '**/*.gemspec'
    - '**/Gemfile'
    - '**/gems.rb'

Metrics/ParameterLists:
  Max: 12

Naming/BlockForwarding:
  Enabled: pending
  EnforcedStyle: explicit
  SupportedStyles:
    - anonymous
    - explicit
  BlockForwardingName: block

Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: snake_case
  SupportedStyles:
    - snake_case
    - normalcase
    - non_integer

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Max: 3

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/NestedGroups:
  Max: 5
